/*
 *  (c) Copyright 2016-2024 Hewlett Packard Enterprise Development Company LP.
 *
 *  This software is available to you under a choice of one of two
 *  licenses. You may choose to be licensed under the terms of the
 *  GNU Lesser General Public License Version 3, or (at your option)
 *  later with exceptions included below, or under the terms of the
 *  MIT license (Expat) available in COPYING file in the source tree.
 *
 *  This program is distributed in the hope that it will be useful,
 *  but WITHOUT ANY WARRANTY; without even the implied warranty of
 *  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *  GNU Lesser General Public License for more details.
 *
 *  You should have received a copy of the GNU Lesser General Public License
 *  along with this program.  If not, see <http://www.gnu.org/licenses/>.
 *
 *  As an exception, the copyright holders of this Library grant you permission
 *  to (i) compile an Application with the Library, and (ii) distribute the
 *  Application containing code generated by the Library and added to the
 *  Application during this compilation process under terms of your choice,
 *  provided you also meet the terms and conditions of the Application license.
 *
 */

#if defined(__x86_64__)
#include <emmintrin.h> // for _mm_clflush
#endif

#include <libpmem.h>
#include <stdint.h>
#include <string.h>

void fam_invalidate(const void *addr, size_t len) {
    const static uintptr_t FLUSH_ALIGN = (uintptr_t)64;
    for (uintptr_t uptr = (uintptr_t)addr & ~(FLUSH_ALIGN - 1);
         uptr < (uintptr_t)addr + len; uptr += FLUSH_ALIGN) {
#ifdef __x86_64__
        _mm_clflush((char *)uptr);
#elif defined(__aarch64__)
        asm volatile("dc\tivac, %0" : : "r"((char *)uptr) : "memory");
#else
#pragma error "No implementation for cache invalidation"
#endif
    }
}

void fam_persist(const void *addr, size_t len) { pmem_persist(addr, len); }

void *fam_memset_persist(void *pmemdest, int c, size_t len) {
    return pmem_memset_persist(pmemdest, c, len);
}

void *fam_memcpy(void *dest, const void *src, size_t n) {
    return memcpy(dest, src, n);
}

int fam_memcmp(const void *s1, const void *s2, size_t n) {
    return memcmp(s1, s2, n);
}

int64_t fam_read_64(const void *addr) { return *((int64_t *)addr); }

void fam_read_128(const void *addr, int64_t val[2]) {
    val[0] = ((int64_t *)addr)[0];
    val[1] = ((int64_t *)addr)[1];
}

void fam_fence() { return; }
